### ISSUE TITLE
Convert whole CLI to GUI

### ISSUE THREAD

**Issue by qaidjoharj53** [qaidjoharj53/Banking_System#11]
Developers intereseted can comment and collaborate.

**Comment by sirKiraUzumaki** [comment]
Im interested to work on it as I have already worked on tkinter with mysql connector

**Comment by qaidjoharj53** [comment]
@sirKiraUzumaki
It's good to know you are interested.
I want a GUI created using PyQt5 instead.

Let me know if you are interested in working upon this issue.

**Comment by sirKiraUzumaki** [comment]
Oh I have some knowledge of PyQt5, I can give it a try.

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @sirKiraUzumaki  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 , @rohitagr0310 , @jain-anshika .

**Comment by sirKiraUzumaki** [comment]
Sure thanks!

**Comment by Kr-Adarsh** [comment]
I've created the GUI for Banking system and a pull request for it. So please review it! @qaidjoharj53 

![Screenshot 2024-10-10 233125](https://github.com/user-attachments/assets/045f14c5-de6e-400e-b3e8-9c4c39391498)
![Screenshot 2024-10-10 233136](https://github.com/user-attachments/assets/deeac09d-ba2e-4dbd-b51e-ba859f029ba6)
