### ISSUE TITLE
Linking banking system to MySQL database

### ISSUE THREAD

**Issue by anishka25** [qaidjoharj53/Banking_System#4]
Can I work on linking this to MySQL database ?

**Comment by qaidjoharj53** [comment]
Go Ahead! I have assigned the issue to you @anishka25  .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @qaidjoharj53 , @rohitagr0310 , @jain-anshika .

**Comment by payallenka** [comment]
hello @anishka25 I would like to collaborate with you on this project. @qaidjoharj53 kindly assign this project to me as well.
I wish to work on the MySQL(backend) along with updating the documentation of this project.

**Comment by anishka25** [comment]
@qaidjoharj53 ,@payallenka I am sorry , I wont be able to collaborate with you on this as only indiviual contributions are counted in hacktoberfest
