### ISSUE TITLE
Error Handling Using Try-Exception Blocks

### ISSUE THREAD

**Issue by Robinrai2612** [qaidjoharj53/Banking_System#5]
@qaidjoharj53   I would like to work on the error handling  enhancement in the file.

**Comment by Robinrai2612** [comment]
@qaidjoharj53 Kindly assign me this issue .

**Comment by rohitagr0310** [comment]
Go Ahead! I have assigned the issue to you @Robinrai2612 .

Work on a new branch with the feature as the branch name.

When you create a pull request, request review from @rohitagr0310 , @jain-anshika or , @qaidjoharj53

**Comment by Robinrai2612** [comment]
@rohitagr0310 Thanks!!

**Comment by rohitagr0310** [comment]
> @rohitagr0310 Thanks!!

You are welcome
